spring.datasource.url=jdbc:mysql://localhost:3306/miutn?useSSL=false&serverTimezone=UTC
spring.datasource.username=bautista
spring.datasource.password=bautista
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

jwt.secret=fd2eda55ed042666f05310975fb4b75c7d44ffd8199496c0f869df02410a9d6a65391938fc2d5496b784b21b5a7ad48abde8f09e0a63c3fc4db4c7ec32b9cf07
jwt.expiration=3600000